---
apiVersion: v1
kind: Namespace
metadata:
  name: service-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-monitoring-deployment
  labels:
    app: service-monitoring
  namespace: service-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-monitoring
  template:
    metadata:
      labels:
        app: service-monitoring
    spec:
      containers:
      - name: service-monitoring
        image: service-monitoring:1.0  #Image Name needs to be updated as per registry used to push the service image
        ports:
        - port: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: service-monitoring
spec:
  type: NodePort
  selector:
    app: service-monitoring
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5000
      targetPort: 5000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---